### PR TITLE
wheee

### PR DESCRIPTION
**Pull request by KingEdwardI**

### CODE REVIEW

**Comment by cc-sarah** [comment]
i don't know if i want to vote for pedro does he like cats?

**Comment by davidmscott** [comment]
This is good, I'm not quitting

**Comment by KellyKapp** [comment]
This election is fair

**Comment by KingEdwardI** [comment]
#Napoleon_Dynamite just to annoy Erty

**Comment by GPSWally** [comment]
This is a dangerous commit..DO NOT DO!!!

**Comment by davidmscott** [comment]
Let me stay!

**Comment by KellyKapp** [comment]
You've been voted off the island

**Pull request merged**
